-- +goose Up
ALTER TABLE users ADD COLUMN email VARCHAR(255) UNIQUE NOT NULL;
ALTER TABLE users ADD COLUMN full_name VARCHAR(255) NOT NULL;

-- +goose Down
ALTER TABLE users DROP COLUMN email;
ALTER TABLE users DROP COLUMN full_name;
